In [1]:
# Q1

import pandas as pd

df = pd.DataFrame({
    "restaurant": ["Dominos", "KFC", "Dominos", "Pizza Hut"],
    "date": ["2025-06-01", "2025-06-02", "2025-06-01", "2025-06-03"]
})

duplicates = df[df.duplicated(subset=["restaurant", "date"])]

print(duplicates)

  restaurant        date
2    Dominos  2025-06-01

In [2]:
# Q2

import pandas as pd

df = pd.DataFrame({
    "review": [
        "Good Product",
        "Excellent",
        "Good Product",
        "Nice",
        "Excellent",
        "Good Product"
    ]
})

print(df["review"].value_counts().head(3))

review
Good Product    3
Excellent       2
Nice            1
Name: count, dtype: int64

In [3]:
# Q3

import pandas as pd

df = pd.DataFrame({
    "playlist": ["Hits", "Rock", "Hits", "Pop"],
    "creator": ["user1", "user2", "user1", "user3"]
})

df = df.drop_duplicates()

df

  playlist creator
0     Hits   user1
1     Rock   user2
3      Pop   user3

In [4]:
# Q4

import pandas as pd

df = pd.DataFrame({
    "username": [
        "insta_queen",
        "insta-queen",
        "instaqueen",
        "insta_queen"
    ]
})

df["username"] = df["username"].replace({
    "insta_queen": "instaqueen",
    "insta-queen": "instaqueen"
})

df

     username
0  instaqueen
1  instaqueen
2  instaqueen
3  instaqueen

In [5]:
# Q5

import pandas as pd

df = pd.DataFrame({
    "status": ["Yes", " yes ", "Y", "No", "no", "N", " Yes "]
})

df["status"] = df["status"].str.strip().str.lower()

df["status"] = df["status"].replace({
    "yes": 1,
    "y": 1,
    "no": 0,
    "n": 0
})

df

C:\Users\Pratham Chauhan\AppData\Local\Temp\ipykernel_2280\1368660245.py:11: FutureWarning: Downcasting behavior in `replace` is deprecated and will be removed in a future version. To retain the old behavior, explicitly call `result.infer_objects(copy=False)`. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  df["status"] = df["status"].replace({

   status
0       1
1       1
2       1
3       0
4       0
5       0
6       1